This is makeindex, version 2.15 [TeX Live 2020/W32TeX] (kpathsea + Thai support).
Scanning style file ./main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn....done (384 entries accepted, 0 rejected).
Sorting entries......done (3599 comparisons).
Generating output file main.acr....done (242 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
